name: Build Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name SubjectSelectionSplitter-Windows --hidden-import PIL._tkinter_finder --hidden-import tkinter --hidden-import tkinter.filedialog --hidden-import tkinter.messagebox --hidden-import tkinter.ttk src/extractor.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: SubjectSelectionSplitter-Windows
          path: dist/SubjectSelectionSplitter-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          brew install tcl-tk
          brew install poppler
      - name: Get Poppler path
        run: |
          echo "POPPLER_PATH=$(brew --prefix poppler)/bin" >> $GITHUB_ENV
      - name: Build with PyInstaller
        run: |
          pyinstaller macos.spec --clean
        env:
          POPPLER_PATH: ${{ env.POPPLER_PATH }}
      - name: Fix permissions
        run: |
          chmod -R 755 dist/SubjectSelectionSplitter-Mac.app
      - name: Copy Poppler libraries
        run: |
          mkdir -p dist/SubjectSelectionSplitter-Mac.app/Contents/Frameworks/
          cp $(brew --prefix poppler)/lib/libpoppler*.dylib dist/SubjectSelectionSplitter-Mac.app/Contents/Frameworks/
      - name: Create ZIP archive
        run: |
          cd dist
          ditto -c -k --keepParent SubjectSelectionSplitter-Mac.app SubjectSelectionSplitter-Mac.zip
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: SubjectSelectionSplitter-Mac
          path: dist/SubjectSelectionSplitter-Mac.zip
