name: Build Executables

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name SubjectSelectionSplitter-Windows src/extractor.py
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: SubjectSelectionSplitter-Windows
          path: dist/SubjectSelectionSplitter-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app
          pip install pyobjc-framework-Cocoa
      - name: Create setup.py
        run: |
          echo 'from setuptools import setup
          
          OPTIONS = {
              "argv_emulation": True,
              "packages": [
                  "PIL",
                  "PyPDF2",
                  "pdf2image",
                  "tkinter",
                  "tqdm",
                  "json",
                  "os",
                  "sys",
                  "io"
              ],
              "includes": [
                  "PIL._tkinter_finder",
                  "tkinter",
                  "tkinter.filedialog",
                  "tkinter.messagebox",
                  "tkinter.ttk"
              ],
              "excludes": ["matplotlib", "numpy"],
              "frameworks": ["Tcl", "Tk"],
              "plist": {
                  "CFBundleName": "SubjectSelectionSplitter",
                  "CFBundleDisplayName": "Subject Selection Splitter",
                  "CFBundleVersion": "1.0.0",
                  "CFBundleIdentifier": "com.ciaranengelbrecht.subjectsplitter",
                  "LSMinimumSystemVersion": "10.10",
                  "NSHighResolutionCapable": True,
                  "NSRequiresAquaSystemAppearance": False
              }
          }
          
          setup(
              name="SubjectSelectionSplitter",
              app=["src/extractor.py"],
              setup_requires=["py2app"],
              options={"py2app": OPTIONS}
          )' > setup.py
      - name: Build macOS app
        run: |
          python setup.py py2app --packages=PIL,PyPDF2,pdf2image,tkinter
      - name: Create ZIP archive
        run: |
          cd dist
          zip -r SubjectSelectionSplitter-Mac.zip SubjectSelectionSplitter.app
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v3
        with:
          name: SubjectSelectionSplitter-Mac
          path: dist/SubjectSelectionSplitter-Mac.zip
